-- USER table
CREATE TABLE USER
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME       VARCHAR(100) NOT NULL,
    LAST_NAME        VARCHAR(100) NOT NULL,
    USERNAME         VARCHAR(100) NOT NULL,
    EMAIL            VARCHAR(150) NOT NULL UNIQUE,
    BIRTH_DATE       DATE,
    INSCRIPTION_DATE DATE
);

-- PRODUCT table
CREATE TABLE PRODUCT
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(50)  NOT NULL,
    NAME VARCHAR(100) NOT NULL
);

-- RECIPE table
CREATE TABLE RECIPE
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE            VARCHAR(255)  NOT NULL,
    DESCRIPTION      VARCHAR(2000) NOT NULL,
    PREPARATION_TIME INT,
    TYPE             VARCHAR(50)   NOT NULL,
    PUBLICATION_DATE DATE,
    USER_ID          BIGINT        NOT NULL,
    CONSTRAINT FK_RECIPE_USER FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

-- INGREDIENT table
CREATE TABLE INGREDIENT
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    QUANTITY   DOUBLE,
    UNIT       VARCHAR(50),
    RECIPE_ID  BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    CONSTRAINT FK_INGREDIENT_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (ID),
    CONSTRAINT FK_INGREDIENT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

-- STEP table
CREATE TABLE STEP
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    STEP_ORDER  INT           NOT NULL,
    RECIPE_ID   BIGINT        NOT NULL,
    CONSTRAINT FK_STEP_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (ID)
);