-- Roles
INSERT INTO ROLE (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (NAME) VALUES ('ROLE_USER');

-- Users
INSERT INTO APP_USER (FIRST_NAME, LAST_NAME, USERNAME, EMAIL, BIRTH_DATE, INSCRIPTION_DATE, PASSWORD)
VALUES ('Admin', 'Admin', 'admin', 'admin@example.com', '1988-03-02', '2024-01-01', '$2a$10$n15EyxawFS7VJYgPf6a5.uLB35S1vWxmow/psJW5NLfWOT93Uvm7a'); -- pwd1234
INSERT INTO APP_USER (FIRST_NAME, LAST_NAME, USERNAME, EMAIL, BIRTH_DATE, INSCRIPTION_DATE, PASSWORD)
VALUES ('Alice', 'Smith', 'asmith', 'alice@example.com', '1990-05-12', '2025-01-01', '$2a$10$n15EyxawFS7VJYgPf6a5.uLB35S1vWxmow/psJW5NLfWOT93Uvm7a'); -- pwd1234
INSERT INTO APP_USER (FIRST_NAME, LAST_NAME, USERNAME, EMAIL, BIRTH_DATE, INSCRIPTION_DATE, PASSWORD)
VALUES ('Bob', 'Johnson', 'bjohnson', 'bob@example.com', '1985-08-20', '2025-02-01', '$2a$10$T2FAXSJo.cGWI94eY0nODe8XxQljzNAqQ2MMTFJ5XS0vS.W.kiiQS'); --pwd5678

-- User Roles
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (3, 2);

-- Products
INSERT INTO PRODUCT (TYPE, NAME) VALUES ('VEGETABLE', 'Carrot');
INSERT INTO PRODUCT (TYPE, NAME) VALUES ('VEGETABLE', 'Potato');
INSERT INTO PRODUCT (TYPE, NAME) VALUES ('MEAT', 'Chicken Breast');
INSERT INTO PRODUCT (TYPE, NAME) VALUES ('DAIRY', 'Cheese');

-- Recipes
INSERT INTO RECIPE (TITLE, DESCRIPTION, PREPARATION_TIME, TYPE, PUBLICATION_DATE, USER_ID)
VALUES ('Roasted Chicken', 'Simple roasted chicken with vegetables', 60, 'MAIN_COURSE', '2025-10-23', 2);

INSERT INTO RECIPE (TITLE, DESCRIPTION, PREPARATION_TIME, TYPE, PUBLICATION_DATE, USER_ID)
VALUES ('Vegetable Soup', 'Healthy mixed vegetable soup', 30, 'STARTER', '2025-10-23', 3);

-- Ingredients
INSERT INTO INGREDIENT (QUANTITY, UNIT, RECIPE_ID, PRODUCT_ID) VALUES (1, 'KILOGRAM', 1, 3); -- Chicken
INSERT INTO INGREDIENT (QUANTITY, UNIT, RECIPE_ID, PRODUCT_ID) VALUES (2, 'PIECE', 1, 1); -- Carrot
INSERT INTO INGREDIENT (QUANTITY, UNIT, RECIPE_ID, PRODUCT_ID) VALUES (3, 'PIECE', 1, 2); -- Potato
INSERT INTO INGREDIENT (QUANTITY, UNIT, RECIPE_ID, PRODUCT_ID) VALUES (500, 'GRAM', 1, 4); -- Cheese

INSERT INTO INGREDIENT (QUANTITY, UNIT, RECIPE_ID, PRODUCT_ID) VALUES (3, 'PIECE', 2, 1); -- Carrot
INSERT INTO INGREDIENT (QUANTITY, UNIT, RECIPE_ID, PRODUCT_ID) VALUES (2, 'PIECE', 2, 2); -- Potato

-- Steps
INSERT INTO STEP (DESCRIPTION, STEP_ORDER, RECIPE_ID) VALUES ('Preheat oven to 180C', 1, 1);
INSERT INTO STEP (DESCRIPTION, STEP_ORDER, RECIPE_ID) VALUES ('Season chicken and vegetables', 2, 1);
INSERT INTO STEP (DESCRIPTION, STEP_ORDER, RECIPE_ID) VALUES ('Roast for 45 minutes', 3, 1);

INSERT INTO STEP (DESCRIPTION, STEP_ORDER, RECIPE_ID) VALUES ('Chop all vegetables', 1, 2);
INSERT INTO STEP (DESCRIPTION, STEP_ORDER, RECIPE_ID) VALUES ('Boil water and add vegetables', 2, 2);
INSERT INTO STEP (DESCRIPTION, STEP_ORDER, RECIPE_ID) VALUES ('Simmer for 20 minutes', 3, 2);