-- ROLE table
CREATE TABLE IF NOT EXISTS ROLE
(
    ID   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

-- USER table
CREATE TABLE IF NOT EXISTS APP_USER
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME       VARCHAR(100) NOT NULL,
    LAST_NAME        VARCHAR(100) NOT NULL,
    USERNAME         VARCHAR(100) NOT NULL,
    EMAIL            VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD         VARCHAR(255) NOT NULL,
    BIRTH_DATE       DATE,
    INSCRIPTION_DATE DATE
);

-- USER_ROLE junction table
CREATE TABLE IF NOT EXISTS USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);

-- PRODUCT table
CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR(50)  NOT NULL,
    NAME VARCHAR(100) NOT NULL
);

-- RECIPE table
CREATE TABLE IF NOT EXISTS RECIPE
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE            VARCHAR(255)  NOT NULL,
    DESCRIPTION      VARCHAR(2000) NOT NULL,
    PREPARATION_TIME INT,
    TYPE             VARCHAR(50)   NOT NULL,
    PUBLICATION_DATE DATE,
    USER_ID          BIGINT        NOT NULL,
    CONSTRAINT FK_RECIPE_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID)
);

-- INGREDIENT table
CREATE TABLE IF NOT EXISTS INGREDIENT
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    QUANTITY   DOUBLE,
    UNIT       VARCHAR(50),
    RECIPE_ID  BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    CONSTRAINT FK_INGREDIENT_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (ID),
    CONSTRAINT FK_INGREDIENT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

-- STEP table
CREATE TABLE IF NOT EXISTS STEP
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(2000) NOT NULL,
    STEP_ORDER  INT           NOT NULL,
    RECIPE_ID   BIGINT        NOT NULL,
    CONSTRAINT FK_STEP_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (ID)
);